server:
  port: 80
spring:
  application:
    name: cloud-consumer-order  #服务名

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://150.158.154.32:8848
  cloud:
    subscribed-services: cloud-provide-payment  #表示要订阅服务的服务名，可以配置'*'代表订阅所有服务（不推荐使用）。若需订阅多应用，使用","分割。